name: check
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        py:
          - 3.9
          - 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}                                                                            
      - name: Setup virtual environment
        run: python -m venv venv
      - name: Setup virtual environment
        run: venv/bin/pip install pytest
      - name: Run test suite
        run: venv/bin/python -m pytest .
